[build]
  command = "cd smart-calendar && npm ci && npx ng build --configuration=production"
  publish = "smart-calendar/dist/smart-calendar"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200